root = "."
tmp_dir = "tmp"
 
[build]
include_ext = [ "go" ]
include_dir = [ "src" ]
cmd = "go build -o ./tmp/caster ./src/..."
full_bin = "./tmp/caster -debug -level 'The Sewers' -res large"

[misc]
clean_on_exit = true